/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package point_of_sale_Systems;

import com.sun.glass.events.KeyEvent;
import java.text.SimpleDateFormat;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;



/**
 *
 * @author DELL
 */
public class point_of_sale_Systems extends javax.swing.JFrame {
    
    String iTax, iSubTotal,iTotal;
    double [] itemcost = new double[26];

    /**
     * Creates new form point_of_sale_Systems
     */
    public point_of_sale_Systems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnApple = new javax.swing.JButton();
        jbtnMeat = new javax.swing.JButton();
        jbtnOrange = new javax.swing.JButton();
        jbtnBacon = new javax.swing.JButton();
        jbtnFish = new javax.swing.JButton();
        jbtnGrapes = new javax.swing.JButton();
        jbtnBroccoli = new javax.swing.JButton();
        jbtnRice = new javax.swing.JButton();
        jbtnTomatoes = new javax.swing.JButton();
        jbtnBeans = new javax.swing.JButton();
        jbtnCucumber = new javax.swing.JButton();
        jbtnCheese = new javax.swing.JButton();
        jbtnCarrots = new javax.swing.JButton();
        jbtnVodka = new javax.swing.JButton();
        jbtnCelery = new javax.swing.JButton();
        jbtnWine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceiptArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jchkApple = new javax.swing.JCheckBox();
        jtxtApple = new javax.swing.JTextField();
        jchkMeat = new javax.swing.JCheckBox();
        jtxtMeat = new javax.swing.JTextField();
        jchkOrange = new javax.swing.JCheckBox();
        jtxtOrange = new javax.swing.JTextField();
        jchkBacon = new javax.swing.JCheckBox();
        jtxtBacon = new javax.swing.JTextField();
        jchkGrapes = new javax.swing.JCheckBox();
        jtxtGrapes = new javax.swing.JTextField();
        jchkFish = new javax.swing.JCheckBox();
        jtxtFish = new javax.swing.JTextField();
        jchkBroccoli = new javax.swing.JCheckBox();
        jtxtBroccoli = new javax.swing.JTextField();
        jchkRice = new javax.swing.JCheckBox();
        jtxtRice = new javax.swing.JTextField();
        jchkTomatoes = new javax.swing.JCheckBox();
        jtxtTomatoes = new javax.swing.JTextField();
        jchkBeans = new javax.swing.JCheckBox();
        jtxtBeans = new javax.swing.JTextField();
        jchkCucumber = new javax.swing.JCheckBox();
        jtxtCucumber = new javax.swing.JTextField();
        jchkCheese = new javax.swing.JCheckBox();
        jtxtCheese = new javax.swing.JTextField();
        jchkCarrots = new javax.swing.JCheckBox();
        jtxtCarrots = new javax.swing.JTextField();
        jchkVodka = new javax.swing.JCheckBox();
        jtxtVodka = new javax.swing.JTextField();
        jchkCelery = new javax.swing.JCheckBox();
        jtxtCelery = new javax.swing.JTextField();
        jchkWine = new javax.swing.JCheckBox();
        jtxtWine = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jbtnApple.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnApple.setForeground(new java.awt.Color(0, 51, 51));
        jbtnApple.setText("Apple");
        jbtnApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAppleActionPerformed(evt);
            }
        });

        jbtnMeat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnMeat.setText("Meat");
        jbtnMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMeatActionPerformed(evt);
            }
        });

        jbtnOrange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnOrange.setText("Orange");
        jbtnOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrangeActionPerformed(evt);
            }
        });

        jbtnBacon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBacon.setText("Bacon");
        jbtnBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBaconActionPerformed(evt);
            }
        });

        jbtnFish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnFish.setText("Fish");
        jbtnFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFishActionPerformed(evt);
            }
        });

        jbtnGrapes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGrapes.setText("Grapes");
        jbtnGrapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGrapesActionPerformed(evt);
            }
        });

        jbtnBroccoli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBroccoli.setText("Broccoli");
        jbtnBroccoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBroccoliActionPerformed(evt);
            }
        });

        jbtnRice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnRice.setText("Rice");
        jbtnRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRiceActionPerformed(evt);
            }
        });

        jbtnTomatoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTomatoes.setText("Tomatoes");
        jbtnTomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTomatoesActionPerformed(evt);
            }
        });

        jbtnBeans.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBeans.setText("Beans");
        jbtnBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBeansActionPerformed(evt);
            }
        });

        jbtnCucumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCucumber.setText("Cucumber");
        jbtnCucumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCucumberActionPerformed(evt);
            }
        });

        jbtnCheese.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCheese.setText("Cheese");
        jbtnCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCheeseActionPerformed(evt);
            }
        });

        jbtnCarrots.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCarrots.setText("Carrots");
        jbtnCarrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCarrotsActionPerformed(evt);
            }
        });

        jbtnVodka.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnVodka.setText("Vodka");
        jbtnVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVodkaActionPerformed(evt);
            }
        });

        jbtnCelery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCelery.setText("Celery");
        jbtnCelery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCeleryActionPerformed(evt);
            }
        });

        jbtnWine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnWine.setText("Wine");
        jbtnWine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWineActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        jLabel1.setText("Categories");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnCarrots, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCelery, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCucumber, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jbtnTomatoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnBroccoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnGrapes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnOrange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnApple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnBacon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnVodka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCheese, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jbtnBeans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnFish, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnMeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnWine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBacon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnApple, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGrapes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnFish, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnBroccoli, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCucumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCheese, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCarrots, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnVodka, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCelery, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnWine, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Tax");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("SubTotal");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Total");

        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jtxtReceiptArea.setColumns(20);
        jtxtReceiptArea.setRows(5);
        jtxtReceiptArea.setText("\n\n\n\n\n\n\n\n");
        jtxtReceiptArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtReceiptAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtReceiptArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jbtnTotal)
                        .addGap(60, 60, 60)
                        .addComponent(jbtnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jbtnExit)))
                .addGap(30, 30, 30))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(207, Short.MAX_VALUE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(52, 52, 52)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(525, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText("jTextField1");

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.setText("jTextField1");

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField8.setText("jTextField1");

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox16.setText("jCheckBox1");

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox19.setText("jCheckBox1");

        jchkApple.setText("Apple");
        jchkApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAppleActionPerformed(evt);
            }
        });

        jtxtApple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAppleKeyTyped(evt);
            }
        });

        jchkMeat.setText("Meat");
        jchkMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMeatActionPerformed(evt);
            }
        });

        jtxtMeat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMeatKeyTyped(evt);
            }
        });

        jchkOrange.setText("Orange");
        jchkOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkOrangeActionPerformed(evt);
            }
        });
        jchkOrange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jchkOrangeKeyTyped(evt);
            }
        });

        jtxtOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtOrangeActionPerformed(evt);
            }
        });
        jtxtOrange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtOrangeKeyTyped(evt);
            }
        });

        jchkBacon.setText("Bacon");
        jchkBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBaconActionPerformed(evt);
            }
        });

        jtxtBacon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBaconKeyTyped(evt);
            }
        });

        jchkGrapes.setText("Grapes");
        jchkGrapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkGrapesActionPerformed(evt);
            }
        });

        jtxtGrapes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGrapesKeyTyped(evt);
            }
        });

        jchkFish.setText("Fish");
        jchkFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkFishActionPerformed(evt);
            }
        });

        jtxtFish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtFishKeyTyped(evt);
            }
        });

        jchkBroccoli.setText("Broccoli");
        jchkBroccoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBroccoliActionPerformed(evt);
            }
        });

        jtxtBroccoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBroccoliKeyTyped(evt);
            }
        });

        jchkRice.setText("Rice");
        jchkRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkRiceActionPerformed(evt);
            }
        });

        jtxtRice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtRiceKeyTyped(evt);
            }
        });

        jchkTomatoes.setText("Tomatoes");
        jchkTomatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkTomatoesActionPerformed(evt);
            }
        });

        jtxtTomatoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTomatoesKeyTyped(evt);
            }
        });

        jchkBeans.setText("Beans");
        jchkBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkBeansActionPerformed(evt);
            }
        });

        jtxtBeans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBeansKeyTyped(evt);
            }
        });

        jchkCucumber.setText("Cucumber");
        jchkCucumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCucumberActionPerformed(evt);
            }
        });

        jtxtCucumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCucumberKeyTyped(evt);
            }
        });

        jchkCheese.setText("Cheese");
        jchkCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCheeseActionPerformed(evt);
            }
        });

        jtxtCheese.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCheeseKeyTyped(evt);
            }
        });

        jchkCarrots.setText("Carrots");
        jchkCarrots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCarrotsActionPerformed(evt);
            }
        });

        jtxtCarrots.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCarrotsKeyTyped(evt);
            }
        });

        jchkVodka.setText("Vodka");
        jchkVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkVodkaActionPerformed(evt);
            }
        });

        jtxtVodka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtVodkaKeyTyped(evt);
            }
        });

        jchkCelery.setText("Celery");
        jchkCelery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCeleryActionPerformed(evt);
            }
        });

        jtxtCelery.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCeleryKeyTyped(evt);
            }
        });

        jchkWine.setText("Wine");
        jchkWine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkWineActionPerformed(evt);
            }
        });

        jtxtWine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtWineKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkApple)
                    .addComponent(jchkOrange)
                    .addComponent(jchkGrapes)
                    .addComponent(jchkBroccoli)
                    .addComponent(jchkTomatoes)
                    .addComponent(jchkCucumber)
                    .addComponent(jchkCarrots)
                    .addComponent(jchkCelery))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtApple, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkMeat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkBacon))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtGrapes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkFish))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtBroccoli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkRice))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkBeans))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtCucumber, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkCheese))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtCarrots, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkVodka))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtCelery, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jchkWine)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtMeat)
                    .addComponent(jtxtBacon)
                    .addComponent(jtxtFish)
                    .addComponent(jtxtRice)
                    .addComponent(jtxtBeans)
                    .addComponent(jtxtCheese)
                    .addComponent(jtxtVodka, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jtxtWine))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(232, Short.MAX_VALUE)
                    .addComponent(jCheckBox16)
                    .addGap(129, 129, 129)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(232, Short.MAX_VALUE)
                    .addComponent(jCheckBox19)
                    .addGap(129, 129, 129)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkApple)
                    .addComponent(jtxtApple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkMeat)
                    .addComponent(jtxtMeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkOrange)
                    .addComponent(jtxtOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkBacon)
                    .addComponent(jtxtBacon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkGrapes)
                    .addComponent(jtxtGrapes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkFish)
                    .addComponent(jtxtFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkBroccoli)
                    .addComponent(jtxtBroccoli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkRice)
                    .addComponent(jtxtRice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkTomatoes)
                    .addComponent(jtxtTomatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkBeans)
                    .addComponent(jtxtBeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkCucumber)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtCucumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jchkCheese)
                        .addComponent(jtxtCheese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkCarrots)
                    .addComponent(jtxtCarrots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkVodka)
                    .addComponent(jtxtVodka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkCelery)
                    .addComponent(jtxtCelery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkWine)
                    .addComponent(jtxtWine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(562, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(476, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(337, Short.MAX_VALUE)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(274, 274, 274)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(509, Short.MAX_VALUE)
                    .addComponent(jCheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(102, 102, 102)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Point of Sale System");

        jLabel3.setBackground(new java.awt.Color(51, 0, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Cost of Item and Receipt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7))
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGap(751, 751, 751))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAppleActionPerformed
        // TODO add your handling code here:
        jchkApple.setEnabled(true);
        
    }//GEN-LAST:event_jbtnAppleActionPerformed

    private void jbtnMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMeatActionPerformed
        // TODO add your handling code here:
        jchkMeat.setEnabled(true);
        
    }//GEN-LAST:event_jbtnMeatActionPerformed

    private void jbtnOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrangeActionPerformed
        // TODO add your handling code here:
        jchkOrange.setEnabled(true);
        
    }//GEN-LAST:event_jbtnOrangeActionPerformed

    private void jbtnBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBaconActionPerformed
        // TODO add your handling code here:
         jchkBacon.setEnabled(true);
    }//GEN-LAST:event_jbtnBaconActionPerformed

    private void jbtnFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFishActionPerformed
        // TODO add your handling code here:
         jchkFish.setEnabled(true);
        
        
    }//GEN-LAST:event_jbtnFishActionPerformed

    private void jbtnGrapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGrapesActionPerformed
        // TODO add your handling code here:
        jchkGrapes.setEnabled(true);
        
    }//GEN-LAST:event_jbtnGrapesActionPerformed

    private void jbtnBroccoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBroccoliActionPerformed
        // TODO add your handling code here:
        jchkBroccoli.setEnabled(true);
    }//GEN-LAST:event_jbtnBroccoliActionPerformed

    private void jbtnRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRiceActionPerformed
        // TODO add your handling code here:
        jchkRice.setEnabled(true);
    }//GEN-LAST:event_jbtnRiceActionPerformed

    private void jbtnTomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTomatoesActionPerformed
        // TODO add your handling code here:
        jchkTomatoes.setEnabled(true);
    }//GEN-LAST:event_jbtnTomatoesActionPerformed

    private void jbtnBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBeansActionPerformed
        // TODO add your handling code here:
        jchkBeans.setEnabled(true);
    }//GEN-LAST:event_jbtnBeansActionPerformed

    private void jbtnCucumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCucumberActionPerformed
        // TODO add your handling code here:
        jchkCucumber.setEnabled(true);
    }//GEN-LAST:event_jbtnCucumberActionPerformed

    private void jbtnCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCheeseActionPerformed
        // TODO add your handling code here:
        jchkCheese.setEnabled(true);
    }//GEN-LAST:event_jbtnCheeseActionPerformed

    private void jbtnCarrotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCarrotsActionPerformed
        // TODO add your handling code here:
        jchkCarrots.setEnabled(true);
    }//GEN-LAST:event_jbtnCarrotsActionPerformed

    private void jbtnVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVodkaActionPerformed
        // TODO add your handling code here:
        jchkVodka.setEnabled(true);
    }//GEN-LAST:event_jbtnVodkaActionPerformed

    private void jbtnCeleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCeleryActionPerformed
        // TODO add your handling code here:
        jchkCelery.setEnabled(true);
    }//GEN-LAST:event_jbtnCeleryActionPerformed

    private void jbtnWineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWineActionPerformed
        // TODO add your handling code here:
        jchkWine.setEnabled(true);
    }//GEN-LAST:event_jbtnWineActionPerformed

    private void jtxtOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtOrangeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtxtOrangeActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jtxtApple.setText("0");
        jtxtBacon.setText("0");
        jtxtBeans.setText("0");
        jtxtBroccoli.setText("0");
        jtxtCarrots.setText("0");
        jtxtCelery.setText("0");
        jtxtCheese.setText("0");
        jtxtCucumber.setText("0");
        jtxtFish.setText("0");
        jtxtGrapes.setText("0");
        jtxtMeat.setText("0");
        jtxtOrange.setText("0");
        jtxtRice.setText("0");
        jtxtSubTotal.setText("0");
        jtxtTax.setText("0");
        jtxtTotal.setText("0");
        jtxtVodka.setText("0");
        jtxtWine.setText("0");
        jtxtTomatoes.setText("0");
        
        jtxtApple.setEnabled(false);
        jtxtBacon.setEnabled(false);
        jtxtBeans.setEnabled(false);
        jtxtBroccoli.setEnabled(false);
        jtxtCelery.setEnabled(false);
        jtxtCarrots.setEnabled(false);
        jtxtCheese.setEnabled(false);
        jtxtCucumber.setEnabled(false);
        jtxtFish.setEnabled(false);
        jtxtGrapes.setEnabled(false);
        jtxtMeat.setEnabled(false);
        jtxtOrange.setEnabled(false);
        jtxtRice.setEnabled(false);
        jtxtVodka.setEnabled(false);
        jtxtWine.setEnabled(false);
        jtxtSubTotal.setEnabled(false);
        jtxtTax.setEnabled(false);
        jtxtTotal.setEnabled(false);
        jtxtCucumber.setEnabled(false);
        jtxtTomatoes.setEnabled(false);
        
        
        
        
        
        
        
        jchkApple.setSelected(false);
        jchkBacon.setSelected(false);
        jchkBeans.setSelected(false);
        jchkBroccoli.setSelected(false);
        jchkCarrots.setSelected(false);
        jchkCelery.setSelected(false);
        jchkCheese.setSelected(false);
        jchkCucumber.setSelected(false);
        jchkFish.setSelected(false);
        jchkGrapes.setSelected(false);
        jchkMeat.setSelected(false);
        jchkOrange.setSelected(false);
        jchkRice.setSelected(false);
        jchkVodka.setSelected(false);
        jchkWine.setSelected(false);
        jchkTomatoes.setSelected(false);
        
        jchkApple.setEnabled(false);
        jchkBacon.setEnabled(false);
        jchkBeans.setEnabled(false);
        jchkBroccoli.setEnabled(false);
        jchkCarrots.setEnabled(false);
        jchkCelery.setEnabled(false);
        jchkCheese.setEnabled(false);
        jchkCucumber.setEnabled(false);
        jchkFish.setEnabled(false);
        jchkGrapes.setEnabled(false);
        jchkMeat.setEnabled(false);
        jchkOrange.setEnabled(false);
        jchkRice.setEnabled(false);
        jchkVodka.setEnabled(false);
        jchkWine.setEnabled(false);
        jchkTomatoes.setEnabled(false);
        
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_jbtnResetActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exite");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of Sale",
         JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           System.exit(0);
        }
        
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtAppleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAppleKeyTyped
        // TODO add your handling code here:
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
            
    }//GEN-LAST:event_jtxtAppleKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jtxtApple.setEnabled(false);
        jtxtBacon.setEnabled(false);
        jtxtBeans.setEnabled(false);
        jtxtBroccoli.setEnabled(false);
        jtxtCarrots.setEnabled(false);
        jtxtCelery.setEnabled(false);
        jtxtCheese.setEnabled(false);
        jtxtCucumber.setEnabled(false);
        jtxtFish.setEnabled(false);
        jtxtGrapes.setEnabled(false);
        jtxtMeat.setEnabled(false);
        jtxtOrange.setEnabled(false);
        jtxtRice.setEnabled(false);
        jtxtVodka.setEnabled(false);
        jtxtWine.setEnabled(false);
        jtxtTomatoes.setEnabled(false);
        jtxtTax.setEnabled(false);
        jtxtSubTotal.setEnabled(false);
        jtxtTotal.setEnabled(false);
        jtxtReceiptArea.setEnabled(false);
        
        jchkApple.setEnabled(false);
        jchkBacon.setEnabled(false);
        jchkBeans.setEnabled(false);
        jchkBroccoli.setEnabled(false);
        jchkCarrots.setEnabled(false);
        jchkCelery.setEnabled(false);
        jchkCheese.setEnabled(false);
        jchkCucumber.setEnabled(false);
        jchkFish.setEnabled(false);
        jchkGrapes.setEnabled(false);
        jchkMeat.setEnabled(false);
        jchkOrange.setEnabled(false);
        jchkRice.setEnabled(false);
        jchkVodka.setEnabled(false);
        jchkWine.setEnabled(false);
        jchkTomatoes.setEnabled(false);
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jchkAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAppleActionPerformed
        if (jchkApple.isSelected())
        {
            jtxtApple.setEnabled(true);
            jtxtApple.setText("");
            jtxtApple.requestFocus();
        }
        else
        {
            jtxtApple.setEnabled(false);
            jtxtApple.setText("0");
        }
    }//GEN-LAST:event_jchkAppleActionPerformed

    private void jchkOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkOrangeActionPerformed
        // TODO add your handling code here:
         if (jchkOrange.isSelected())
        {
            jtxtOrange.setEnabled(true);
            jtxtOrange.setText("");
            jtxtOrange.requestFocus();
        }
        else
        {
            jtxtOrange.setEnabled(false);
            jtxtOrange.setText("0");
        }
    }//GEN-LAST:event_jchkOrangeActionPerformed

    private void jchkMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMeatActionPerformed
        // TODO add your handling code here:
         if (jchkMeat.isSelected())
        {
            jtxtMeat.setEnabled(true);
            jtxtMeat.setText("");
            jtxtMeat.requestFocus();
        }
        else
        {
            jtxtMeat.setEnabled(false);
            jtxtMeat.setText("0");
        }
    }//GEN-LAST:event_jchkMeatActionPerformed

    private void jchkBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBaconActionPerformed
        // TODO add your handling code here:
         if (jchkBacon.isSelected())
        {
            jtxtBacon.setEnabled(true);
            jtxtBacon.setText("");
            jtxtBacon.requestFocus();
        }
        else
        {
            jtxtBacon.setEnabled(false);
            jtxtBacon.setText("0");
        }
    }//GEN-LAST:event_jchkBaconActionPerformed

    private void jchkGrapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkGrapesActionPerformed
        // TODO add your handling code here:
         if (jchkGrapes.isSelected())
        {
            jtxtGrapes.setEnabled(true);
            jtxtGrapes.setText("");
            jtxtGrapes.requestFocus();
        }
        else
        {
            jtxtGrapes.setEnabled(false);
            jtxtGrapes.setText("0");
        }
    }//GEN-LAST:event_jchkGrapesActionPerformed

    private void jchkFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkFishActionPerformed
        // TODO add your handling code here:
         if (jchkFish.isSelected())
        {
            jtxtFish.setEnabled(true);
            jtxtFish.setText("");
            jtxtFish.requestFocus();
        }
        else
        {
            jtxtFish.setEnabled(false);
            jtxtFish.setText("0");
        }
    }//GEN-LAST:event_jchkFishActionPerformed

    private void jchkBroccoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBroccoliActionPerformed
        // TODO add your handling code here:
         if (jchkBroccoli.isSelected())
        {
            jtxtBroccoli.setEnabled(true);
            jtxtBroccoli.setText("");
            jtxtBroccoli.requestFocus();
        }
        else
        {
            jtxtBroccoli.setEnabled(false);
            jtxtBroccoli.setText("0");
        }
    }//GEN-LAST:event_jchkBroccoliActionPerformed

    private void jchkRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkRiceActionPerformed
        // TODO add your handling code here:
         if (jchkRice.isSelected())
        {
            jtxtRice.setEnabled(true);
            jtxtRice.setText("");
            jtxtRice.requestFocus();
        }
        else
        {
            jtxtRice.setEnabled(false);
            jtxtRice.setText("0");
        }
    }//GEN-LAST:event_jchkRiceActionPerformed

    private void jchkTomatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkTomatoesActionPerformed
        // TODO add your handling code here:
         if (jchkTomatoes.isSelected())
        {
            jtxtTomatoes.setEnabled(true);
            jtxtTomatoes.setText("");
            jtxtTomatoes.requestFocus();
        }
        else
        {
            jtxtTomatoes.setEnabled(false);
            jtxtTomatoes.setText("0");
        }
    }//GEN-LAST:event_jchkTomatoesActionPerformed

    private void jchkBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkBeansActionPerformed
        // TODO add your handling code here:
         if (jchkBeans.isSelected())
        {
            jtxtBeans.setEnabled(true);
            jtxtBeans.setText("");
            jtxtBeans.requestFocus();
        }
        else
        {
            jtxtBeans.setEnabled(false);
            jtxtBeans.setText("0");
        }
    }//GEN-LAST:event_jchkBeansActionPerformed

    private void jchkCucumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCucumberActionPerformed
        // TODO add your handling code here:
         if (jchkCucumber.isSelected())
        {
            jtxtCucumber.setEnabled(true);
            jtxtCucumber.setText("");
            jtxtCucumber.requestFocus();
        }
        else
        {
            jtxtCucumber.setEnabled(false);
            jtxtCucumber.setText("0");
        }
    }//GEN-LAST:event_jchkCucumberActionPerformed

    private void jchkCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCheeseActionPerformed
        // TODO add your handling code here:
         if (jchkCheese.isSelected())
        {
            jtxtCheese.setEnabled(true);
            jtxtCheese.setText("");
            jtxtCheese.requestFocus();
        }
        else
        {
            jtxtCheese.setEnabled(false);
            jtxtCheese.setText("0");
        }
    }//GEN-LAST:event_jchkCheeseActionPerformed

    private void jchkCarrotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCarrotsActionPerformed
        // TODO add your handling code here:
         if (jchkCarrots.isSelected())
        {
            jtxtCarrots.setEnabled(true);
            jtxtCarrots.setText("");
            jtxtCarrots.requestFocus();
        }
        else
        {
            jtxtCarrots.setEnabled(false);
            jtxtCarrots.setText("0");
        }
    }//GEN-LAST:event_jchkCarrotsActionPerformed

    private void jchkVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkVodkaActionPerformed
        // TODO add your handling code here:
         if (jchkVodka.isSelected())
        {
            jtxtVodka.setEnabled(true);
            jtxtVodka.setText("");
            jtxtVodka.requestFocus();
        }
        else
        {
            jtxtVodka.setEnabled(false);
            jtxtVodka.setText("0");
        }
    }//GEN-LAST:event_jchkVodkaActionPerformed

    private void jchkCeleryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCeleryActionPerformed
        // TODO add your handling code here:
         if (jchkCelery.isSelected())
        {
            jtxtCelery.setEnabled(true);
            jtxtCelery.setText("");
            jtxtCelery.requestFocus();
        }
        else
        {
            jtxtCelery.setEnabled(false);
            jtxtCelery.setText("0");
        }
    }//GEN-LAST:event_jchkCeleryActionPerformed

    private void jchkWineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkWineActionPerformed
        // TODO add your handling code here:
         if (jchkWine.isSelected())
        {
            jtxtWine.setEnabled(true);
            jtxtWine.setText("");
            jtxtWine.requestFocus();
        }
        else
        {
            jtxtWine.setEnabled(false);
            jtxtWine.setText("0");
        }
    }//GEN-LAST:event_jchkWineActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        itemcost[0] = Double.parseDouble(jtxtApple.getText())*1.50;
        itemcost[1] = Double.parseDouble(jtxtBroccoli.getText())*1.80;
        itemcost[2] = Double.parseDouble(jtxtOrange.getText())*1.90;
        itemcost[3] = Double.parseDouble(jtxtMeat.getText())*2.50; 
        itemcost[4] = Double.parseDouble(jtxtBacon.getText())*3.50;
        itemcost[5] = Double.parseDouble(jtxtGrapes.getText())*1.70;
        itemcost[6] = Double.parseDouble(jtxtFish.getText())*2.50;
        itemcost[7] = Double.parseDouble(jtxtRice.getText())*1.50;
        itemcost[8] = Double.parseDouble(jtxtTomatoes.getText())*3.50;
        itemcost[9] = Double.parseDouble(jtxtBeans.getText())*1.50;
        itemcost[10] = Double.parseDouble(jtxtCucumber.getText())*1.50;
        itemcost[11] = Double.parseDouble(jtxtCheese.getText())*2.50;
        itemcost[12] = Double.parseDouble(jtxtCarrots.getText())*1.70;
        itemcost[13] = Double.parseDouble(jtxtVodka.getText())*2.50;
        itemcost[14] = Double.parseDouble(jtxtCelery.getText())*1.50;
        itemcost[15] = Double.parseDouble(jtxtWine.getText())*2.70;
        
        itemcost[22]= itemcost[0] +  itemcost[1] +  itemcost[2] +  itemcost[3] +  itemcost[4] + itemcost[5] + itemcost[6];
        itemcost[23]= itemcost[7] +  itemcost[8] +  itemcost[9] +  itemcost[10] +  itemcost[11] + itemcost[12] + itemcost[13];
        itemcost[24]= itemcost[14]+  itemcost[15] +  itemcost[16] +  itemcost[17] + itemcost[18] +  itemcost[19] +  itemcost[20];
        itemcost[25]= itemcost[21]+  itemcost[22] +  itemcost[23] +  itemcost[24];
       
        
        
        iTax = String.format("£ %.2f ", itemcost[25] / 100);
        iSubTotal = String.format("£ %.2f ", itemcost[25]);
        iTotal = String.format("£ %.2f ", itemcost[25] + (itemcost[25] / 100));
        
        jtxtTax.setText(iTax);
        jtxtSubTotal.setText(iSubTotal);
        jtxtTotal.setText(iTotal);
        
        
        //////////////////////////////////
        jtxtReceiptArea.setEnabled(true);
        //================================================================
     int refs= 1325 + (int) (Math.random()*4238);
     //int ref = (refs);
     //==================================================================
     
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-YYY");
        Tdate.format(timer.getTime());
 //========================================================================
   jtxtReceiptArea.append("\tpoint of sale Management Systems\n" +
         "Reference:\t\t\t\t" + refs +
         "\n=================================================\t" +
         
             "\n=============================================\t" +
             "\nTax:\t\t\t\t\t" + iTax +
             "\nSub Total:\t\t\t\t" + iSubTotal +
             "\nTotal:\t\t\t\t\t" + iTotal +
             "\n================================================\t" +
             "\nDate:" + Tdate.format(timer.getTime()) +
                     "\t\tTime:" + tTime.format(timer.getTime()) +
         "\n\n\tThank you for shopping at iShop\n");
    
        
        
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jchkOrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkOrangeKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jchkOrangeKeyTyped

    private void jtxtGrapesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGrapesKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtGrapesKeyTyped

    private void jtxtOrangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtOrangeKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtOrangeKeyTyped

    private void jtxtMeatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMeatKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtMeatKeyTyped

    private void jtxtBaconKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBaconKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtBaconKeyTyped

    private void jtxtFishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFishKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtFishKeyTyped

    private void jtxtBroccoliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBroccoliKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtBroccoliKeyTyped

    private void jtxtRiceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtRiceKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtRiceKeyTyped

    private void jtxtTomatoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTomatoesKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtTomatoesKeyTyped

    private void jtxtBeansKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBeansKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtBeansKeyTyped

    private void jtxtCucumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCucumberKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtCucumberKeyTyped

    private void jtxtCheeseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCheeseKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtCheeseKeyTyped

    private void jtxtCarrotsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCarrotsKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtCarrotsKeyTyped

    private void jtxtVodkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtVodkaKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtVodkaKeyTyped

    private void jtxtCeleryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCeleryKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtCeleryKeyTyped

    private void jtxtWineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtWineKeyTyped
        // TODO add your handling code here:
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
        ||(iNumber == KeyEvent.VK_BACKSPACE)
        ||(iNumber == KeyEvent.VK_DELETE)){
         evt.consume();
        }
       
    }//GEN-LAST:event_jtxtWineKeyTyped

    private void jtxtReceiptAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtReceiptAreaKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtxtReceiptAreaKeyTyped

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(point_of_sale_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(point_of_sale_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(point_of_sale_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(point_of_sale_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new point_of_sale_Systems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton jbtnApple;
    private javax.swing.JButton jbtnBacon;
    private javax.swing.JButton jbtnBeans;
    private javax.swing.JButton jbtnBroccoli;
    private javax.swing.JButton jbtnCarrots;
    private javax.swing.JButton jbtnCelery;
    private javax.swing.JButton jbtnCheese;
    private javax.swing.JButton jbtnCucumber;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFish;
    private javax.swing.JButton jbtnGrapes;
    private javax.swing.JButton jbtnMeat;
    private javax.swing.JButton jbtnOrange;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnRice;
    private javax.swing.JButton jbtnTomatoes;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JButton jbtnVodka;
    private javax.swing.JButton jbtnWine;
    private javax.swing.JCheckBox jchkApple;
    private javax.swing.JCheckBox jchkBacon;
    private javax.swing.JCheckBox jchkBeans;
    private javax.swing.JCheckBox jchkBroccoli;
    private javax.swing.JCheckBox jchkCarrots;
    private javax.swing.JCheckBox jchkCelery;
    private javax.swing.JCheckBox jchkCheese;
    private javax.swing.JCheckBox jchkCucumber;
    private javax.swing.JCheckBox jchkFish;
    private javax.swing.JCheckBox jchkGrapes;
    private javax.swing.JCheckBox jchkMeat;
    private javax.swing.JCheckBox jchkOrange;
    private javax.swing.JCheckBox jchkRice;
    private javax.swing.JCheckBox jchkTomatoes;
    private javax.swing.JCheckBox jchkVodka;
    private javax.swing.JCheckBox jchkWine;
    private javax.swing.JTextField jtxtApple;
    private javax.swing.JTextField jtxtBacon;
    private javax.swing.JTextField jtxtBeans;
    private javax.swing.JTextField jtxtBroccoli;
    private javax.swing.JTextField jtxtCarrots;
    private javax.swing.JTextField jtxtCelery;
    private javax.swing.JTextField jtxtCheese;
    private javax.swing.JTextField jtxtCucumber;
    private javax.swing.JTextField jtxtFish;
    private javax.swing.JTextField jtxtGrapes;
    private javax.swing.JTextField jtxtMeat;
    private javax.swing.JTextField jtxtOrange;
    private javax.swing.JTextArea jtxtReceiptArea;
    private javax.swing.JTextField jtxtRice;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTomatoes;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVodka;
    private javax.swing.JTextField jtxtWine;
    // End of variables declaration//GEN-END:variables
}
